### ISSUE TITLE
Installation on docker jupyterhub/k8s-singleuser-sample:1.1.3-n248.h20c9028e  fails

### ISSUE THREAD

**Issue by skoulouzis** [adokter/vol2birdinstall#11]
Running:
```Dockerfile
RUN mkdir -p /opt/vol2bird
RUN chown $NB_USER /opt/vol2bird
RUN git clone https://github.com/adokter/vol2birdinstall.git
WORKDIR vol2birdinstall
RUN ./setup install
```
We get an error:
```
Installing iris2odim....Cloning into 'iris2odim'...
Already up to date.
Note: switching to '376ae90cf93baafe225e4d394f634fd178e9a238'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 376ae90 added a comment
fatal: No names found, cannot describe anything.
IRIS2ODIM is at version: 376ae90cf93baafe225e4d394f634fd178e9a238
./setup: 401: patch: not found
(RAVE) Could not patch system for building
The command '/bin/bash -o pipefail -c ./setup install' returned a non-zero code: 127
```

Base image: FROM jupyterhub/k8s-singleuser-sample:1.1.3-n248.h20c9028e 
Image details:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by adokter** [comment]
@andershenja can this one be closed after your latest commits?

**Comment by andershenja** [comment]
Just verified that it can be installed on a docker ubuntu20.04 image. From above printouts it seems like the command "patch" is missing. Have you any possibility to provide enough instructions so that I can reproduce it?

**Comment by adokter** [comment]
A missing `patch` command could explain this issue, which should be part of a default ubuntu install. @skoulouzis could you verify if that solves your issue? Please reopen if the problem persists
