### ISSUE TITLE
libproj.so.0 needed on rocky install

### ISSUE THREAD

**Issue by gkeane** [adokter/vol2birdinstall#16]
We're switching to rocky linux 8 and getting the below from running the installer.
Any help is appreciated.

# ------------------------------------
#       linking vol2bird
# ------------------------------------
#
/usr/bin/c++    -o vol2bird vol2bird.o \
-L/opt/vol2bird/rave/lib -L/opt/vol2bird/hlhdf/lib   -L/opt/vol2bird/lib \
-L/opt/vol2bird/lib \
-L/opt/vol2bird/rsl/lib \
-L/usr/lib64 \
-I/opt/vol2bird/libtorch/include \
-L/opt/vol2bird/libtorch/lib -L../libmistnet \
-lvol2bird -lravetoolbox -lhlhdf -lproj -lpthread -lm -lgsl -lrsl   -L../lib -lmistnet -ltorch -lc10
/usr/bin/ld: warning: libproj.so.0, needed by /usr/lib64/libvol2bird.so, not found (try using -rpath or -rpath-link)
vol2bird.o: In function `main':
/home/gkeane/vol2birdinstall/.build/vol2bird/src/vol2bird.c:106: undefined reference to `libvol2bird_version'
/home/gkeane/vol2birdinstall/.build/vol2bird/src/vol2bird.c:263: undefined reference to `isRegularFile'
/home/gkeane/vol2birdinstall/.build/vol2bird/src/vol2bird.c:271: undefined reference to `isRegularFile'
/home/gkeane/vol2birdinstall/.build/vol2bird/src/vol2bird.c:332: undefined reference to `PolarVolume_resample'
/home/gkeane/vol2birdinstall/.build/vol2bird/src/vol2bird.c:320: undefined reference to `vol2birdLoadClutterMap'
/home/gkeane/vol2birdinstall/.build/vol2bird/src/vol2bird.c:107: undefined reference to `libvol2bird_version'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:70: vol2bird] Error 1
make[1]: Leaving directory '/home/gkeane/vol2birdinstall/.build/vol2bird/src'
make: *** [Makefile:33: build] Error 2
(VOL2BIRD) Failed to compile software

**Comment by adokter** [comment]
Hi, we haven't tested on Rocky Linux before. It might be a linking issue with your file /usr/lib64/libvol2bird.so, could this be a remnant of a previous installation? The default install directory is /opt/vol2bird, so I wouldn't expect this file in /usr/lib64. I would remove this file, and start your build using vol2birdinstall from scratch with:

```
./setup clean
./setup distclean
./setup install
```

**Comment by adokter** [comment]
closed by 52bcab16915ed52c88a1ffbbcc6ff61ff11f816a
