### ISSUE TITLE
Install vol2bird

### ISSUE THREAD

**Issue by yangning-cuit** [adokter/vol2birdinstall#17]
We're switching to ubuntu22.04 and getting the below from running the installer. Any help is appreciated.

gcc -shared -o libiris2odim.so iris2odim_main.o iris2odim.o iris2list.o dlist.o
gcc -I.   -I/opt/vol2bird/hlhdf/include -I/usr/include -I/usr/include/hdf5/serial -I/opt/vol2bird/include -I/opt/vol2bird/rave/include -L. -L/opt/vol2bird/hlhdf/lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu/hdf5/serial -L/opt/vol2bird/lib -L/opt/vol2bird/rave/lib -o iris2odim iris2odim_main.o iris2odim.o iris2list.o dlist.o -liris2odim -lravetoolbox -lhlhdf -lproj -lpthread -lm
/usr/bin/ld: /opt/vol2bird/rave/lib/libravetoolbox.so: undefined reference to `pj_fwd'
/usr/bin/ld: /opt/vol2bird/rave/lib/libravetoolbox.so: undefined reference to `pj_free'
/usr/bin/ld: /opt/vol2bird/rave/lib/libravetoolbox.so: undefined reference to `pj_inv'
/usr/bin/ld: /opt/vol2bird/rave/lib/libravetoolbox.so: undefined reference to `pj_init_plus'
/usr/bin/ld: /opt/vol2bird/rave/lib/libravetoolbox.so: undefined reference to `pj_is_latlong'
/usr/bin/ld: /opt/vol2bird/rave/lib/libravetoolbox.so: undefined reference to `pj_transform'
collect2: error: ld returned 1 exit status

**Comment by adokter** [comment]
Hi there, could you try installing the latest version of proj by hand?
see https://proj.org/

@andershenja any thoughts?

**Comment by yangning-cuit** [comment]
> Hi there, could you try installing the latest version of proj by hand? see https://proj.org/
> 
> @andershenja any thoughts?

I downloaded and installed proj manually, but the problem is still not resolved. Also tried many other methods.

**Comment by adokter** [comment]
Hi @yangning-cuit, this should now be fixed (see 506e7aadf8583ae9b31fa0f4f3a92a68b888f7e3), closing the issue
